name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.2, 8.1, 7.4, 7.3]
        phpunit: ['8.4', '9.6', '10.0', '11.0']
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - php: 7.3
            phpunit: '9.6'
          - php: 7.3
            phpunit: '10.0'
          - php: 7.3
            phpunit: '11.0'
          - php: 7.4
            phpunit: '9.6'
          - php: 7.4
            phpunit: '10.0'
          - php: 7.4
            phpunit: '11.0'

    name: PHP ${{ matrix.php }} - PHPUnit ${{ matrix.phpunit }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --with="phpunit/phpunit:^${{ matrix.phpunit }}"

      - name: Execute tests
        run: vendor/bin/phpunit
